// <auto-generated />
using System;
using DoAnASP.Areas.User.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DoAnASP.Migrations
{
    [DbContext(typeof(DpContext))]
    partial class DpContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DoAnASP.Areas.Admin.Models.BinhLuan", b =>
                {
                    b.Property<int>("IDBL")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IDBV")
                        .HasColumnType("int");

                    b.Property<int?>("IDBlog")
                        .HasColumnType("int");

                    b.Property<int>("IDCH")
                        .HasColumnType("int");

                    b.Property<int?>("IDCauHoi")
                        .HasColumnType("int");

                    b.Property<int>("IDTK")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("IDBL");

                    b.HasIndex("IDBlog");

                    b.HasIndex("IDCauHoi");

                    b.HasIndex("IDTK");

                    b.ToTable("BinhLuans");
                });

            modelBuilder.Entity("DoAnASP.Areas.Admin.Models.Blog", b =>
                {
                    b.Property<int>("IDBlog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IDLoai")
                        .HasColumnType("int");

                    b.Property<int>("IDNguoiDuyet")
                        .HasColumnType("int");

                    b.Property<int>("IDNguoiTao")
                        .HasColumnType("int");

                    b.Property<int?>("IDTK")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDuyet")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuDe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TomTat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.Property<int>("View")
                        .HasColumnType("int");

                    b.HasKey("IDBlog");

                    b.HasIndex("IDLoai");

                    b.HasIndex("IDTK");

                    b.ToTable("Blogs");
                });

            modelBuilder.Entity("DoAnASP.Areas.Admin.Models.CauHoi", b =>
                {
                    b.Property<int>("IDBlog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IDLoai")
                        .HasColumnType("int");

                    b.Property<int>("IDNguoiDuyet")
                        .HasColumnType("int");

                    b.Property<int>("IDNguoiTao")
                        .HasColumnType("int");

                    b.Property<int?>("IDTK")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDuyet")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuDe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TomTat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.Property<int>("View")
                        .HasColumnType("int");

                    b.HasKey("IDBlog");

                    b.HasIndex("IDLoai");

                    b.HasIndex("IDTK");

                    b.ToTable("CauHois");
                });

            modelBuilder.Entity("DoAnASP.Areas.Admin.Models.Loai", b =>
                {
                    b.Property<int>("IDLoai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IDNguoiTao")
                        .HasColumnType("int");

                    b.Property<int?>("IDTK")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TieuDe")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDLoai");

                    b.HasIndex("IDTK");

                    b.ToTable("Loais");
                });

            modelBuilder.Entity("DoAnASP.Areas.Admin.Models.TaiKhoan", b =>
                {
                    b.Property<int>("IDTK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quyen")
                        .HasColumnType("int");

                    b.Property<string>("Ten")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("IDTK");

                    b.ToTable("TaiKhoans");
                });

            modelBuilder.Entity("DoAnASP.Areas.Admin.Models.BinhLuan", b =>
                {
                    b.HasOne("DoAnASP.Areas.Admin.Models.Blog", "blogs")
                        .WithMany()
                        .HasForeignKey("IDBlog");

                    b.HasOne("DoAnASP.Areas.Admin.Models.CauHoi", "cauhois")
                        .WithMany()
                        .HasForeignKey("IDCauHoi");

                    b.HasOne("DoAnASP.Areas.Admin.Models.TaiKhoan", "taiKhoans")
                        .WithMany()
                        .HasForeignKey("IDTK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DoAnASP.Areas.Admin.Models.Blog", b =>
                {
                    b.HasOne("DoAnASP.Areas.Admin.Models.Loai", "loai")
                        .WithMany("blogs")
                        .HasForeignKey("IDLoai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAnASP.Areas.Admin.Models.TaiKhoan", "taikhoans")
                        .WithMany()
                        .HasForeignKey("IDTK");
                });

            modelBuilder.Entity("DoAnASP.Areas.Admin.Models.CauHoi", b =>
                {
                    b.HasOne("DoAnASP.Areas.Admin.Models.Loai", "loai")
                        .WithMany("cauhois")
                        .HasForeignKey("IDLoai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAnASP.Areas.Admin.Models.TaiKhoan", "taikhoans")
                        .WithMany()
                        .HasForeignKey("IDTK");
                });

            modelBuilder.Entity("DoAnASP.Areas.Admin.Models.Loai", b =>
                {
                    b.HasOne("DoAnASP.Areas.Admin.Models.TaiKhoan", "loai")
                        .WithMany()
                        .HasForeignKey("IDTK");
                });
#pragma warning restore 612, 618
        }
    }
}
